# Generated by Django 3.1.7 on 2021-04-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingyourwallet', '0002_auto_20210422_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=266),
        ),
    ]
