# Generated by Django 3.1.7 on 2021-04-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingyourwallet', '0004_source_userincome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
